version: '3.9'

services:
  web:
    build: .
    container_name: nuxt-web
    ports:
      - "3000:3000"
    depends_on:
      - db

    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}


  db:
    image: postgres:15-alpine

    container_name: nuxt-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
